[project]
name = "checker"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "enochecker-core",
    "enochecker3",
]

[dependency-groups]
dev = [
    "mypy==1.14.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
    "ty>=0.0.83",
]

[tool.uv]
override-dependencies = [
    "enochecker-core @ git+https://git.atklab.cloud/atklab/enochecker-core@v0.19.0",
]

[tool.uv.sources]
enochecker-core = { git = "https://git.atklab.cloud/atklab/enochecker-core", rev = "v0.19.0" }
enochecker3 = { git = "https://git.atklab.cloud/atklab/enochecker3", rev = "v0.21.0" }

[tool.ruff]
line-length = 160

[tool.ruff.lint]
extend-select = ["I"]
